apiVersion: v1
kind: Namespace
metadata:
  name: galera
---
apiVersion: v1
kind: Secret
metadata:
  name: galera-secret
  namespace: galera
type: Opaque
data:
  mariadb-root-password: cGFzc3dvcmQ=
  mariadb-password: cGFzc3dvcmQ=
  mariadb-galera-mariabackup-password: cGFzc3dvcmQ=
